### ISSUE TITLE
I got issues on Edit User profile after assigning Role to a user.

### ISSUE THREAD

**Issue by zenepay** [Althinect/filament-spatie-roles-permissions#106]
SQLSTATE[HY000]: General error: 1364 Field 'team_id' doesn't have a default value
```
INSERT INTO
  `model_has_roles` (`model_id`, `model_type`, `role_id`)
VALUES
  (1, App \ Models \ USER, 1)``
```

Please advise what I would do for this case.

**Comment by tharindarodrigo** [comment]
Are you using tenancy in Filament?

**Comment by zenepay** [comment]
No I am not using tenancy. 
My system uses Jetstream with Team.
I found that when I edit Role and select Team, it won't save team_id to its database table roles. The field team_id is Null.

**Comment by zenepay** [comment]
```
I modified the file Althinect\FilamentSpatieRolesPermissions\Resources\RoleResources.php with
$fomr ..->  Select::make(config('permission.column_names.team_foreign_key', 'team_id'))
                                    ->label(__('filament-spatie-roles-permissions::filament-spatie.field.team'))
                                    ->hidden(fn () => ! config('permission.teams', false) || Filament::hasTenancy())
                                    ->options(
                                        fn () => config('filament-spatie-roles-permissions.team_model', App\Models\Team::class)::pluck('name', 'id')
                                    )
                                    //->dehydrated(fn ($state) => (int) $state <= 0)
                                    ->placeholder(__('filament-spatie-roles-permissions::filament-spatie.select-team'))
                                    ->hint(__('filament-spatie-roles-permissions::filament-spatie.select-team-hint')),
                                    
```
By removing ->dehydrated() , then it works. I wonder why its state matters?

**Comment by zenepay** [comment]
Since I cannot make it work with Team, so I change permission.php team=>false, then alter the table model_has_roles for field team_id to accept Null value. This works for me. But I lost role permission for team feature.

**Comment by tharindarodrigo** [comment]
@zenepay I have made some changes, but I haven't specifically tested this. Can please check if this still prevails?

**Comment by yughoz** [comment]
I got issues on 
Create and Edit User
 i'm using in UserResource 
 
Select::make('roles')->multiple()->relationship('roles', 'name')

I'm using tenancy = true

and in menu Attach Users 
"I am experiencing the same problem."

![Screenshot 2023-12-15 at 17 00 14](https://github.com/Althinect/filament-spatie-roles-permissions/assets/14834359/e10c1329-7c4d-46e6-b959-ba70ffb07e28)



![image](https://github.com/Althinect/filament-spatie-roles-permissions/assets/14834359/b1a8f2a8-dc7e-4b81-99eb-095b16782d75)

**Comment by tharindarodrigo** [comment]
Read the docs
