### ISSUE TITLE
How can shown for super admin

### ISSUE THREAD

**Issue by semno** [Althinect/filament-spatie-roles-permissions#111]
How can permissions / roles be shown only to the super admin,

this below image can any user level see it

<img width="308" alt="Screenshot 2023-11-07 at 12 29 06 AM" src="https://github.com/Althinect/filament-spatie-roles-permissions/assets/20298917/2f1f7cf5-1d38-4c6d-9bcc-5b41800c5452">

**Comment by iBet7o** [comment]
What I did to make it work is to create the **Role** and **Permission** models in **App\Models**, extending them from the Spatie models as follows.

**Role Model**

```php
<?php

declare(strict_types=1);

namespace App\Models;

use Spatie\Permission\Models\Role as ModelsRole;

class Role extends ModelsRole
{
}
```

**Permission Model**

```php
<?php

declare(strict_types=1);

namespace App\Models;

use Spatie\Permission\Models\Permission as ModelsPermission;

class Permission extends ModelsPermission
{
}
```

Finally, update the configuration in the permission.php file as follows:

```php
return [

    'models' => [

        ...
        'permission' => App\Models\Permission::class,

        ...
        'role' => App\Models\Role::class,
        
        ...
```

**Comment by tharindarodrigo** [comment]
@iBet7o create policies for Role and Permission models and register them in the AuthServiceProvider.
If you are not Familiar with policies, I suggest you refer the documentations on both Laravel and Filament.

**Comment by iBet7o** [comment]
@tharindarodrigo Thank you for the tip, I've made the change in the **AuthServiceProvider** file and everything works fine.

Regards.

**Comment by tudorr89** [comment]
hello there and thanks for this great package! I've created models for role and permission and added policies for them in authserviceprovider, but the menu items still appear. Do you have a small sample on how to do this?

**Comment by drbyte** [comment]
https://github.com/Althinect/filament-spatie-roles-permissions/issues/118#issuecomment-1806431952
