### ISSUE TITLE
How do I filter 'should_register_on_navigation' by role?

### ISSUE THREAD

**Issue by epertinez** [Althinect/filament-spatie-roles-permissions#117]
I have a problem that I assume must be very silly because I don't see how can it work without this.

I have 'should_register_on_navigation' set to true for both 'permisions' and 'roles' but... that makes roles and permitions apper to all users, not only super-admin!
Mu NavigationMenuMiddleware is heavily twiked depending on user's hasRole, but as far as I see it something is wrong because those two options appear regardless of what I tell the menu to be.

class NavigationMenuMiddleware
{
    public function handle(Request $request, Closure $next): Response
    {
...

 if (auth()->user()->hasRole("sat")) {

            Filament::navigation(function (NavigationBuilder $builder): NavigationBuilder {
               // echo "hola".Request::getPathInfo();
                return $builder->items([
                    NavigationItem::make('Rmas')
                        ->label('Solicitudes')
                        ->icon('heroicon-o-home')
                        ->activeIcon('heroicon-s-home')
                        ->isActiveWhen(fn (): bool => request()->routeIs('filament.app.resources.rmas.index'))
                        ->url(route('filament.app.resources.rmas.index'))
                        ,
                        NavigationItem::make('Artículos')
                            ->url('/reparaciones/articles', shouldOpenInNewTab: false)
                            ->isActiveWhen(fn (): bool => request()->routeIs('filament.pages.articles'))
                            ->icon('heroicon-o-gift')
                            ->activeIcon('heroicon-s-gift')
                            ->sort(3)
                ]);;
            });
...
     }
}

How is it that permisions and roles keep appearing in the menu? How can I tell the plugin what roles to show itself and what roles not.

**Comment by drbyte** [comment]
See #118
