### ISSUE TITLE
Clarification of documentation of polices

### ISSUE THREAD

**Issue by epertinez** [Althinect/filament-spatie-roles-permissions#118]
In your plugin page you say...

[#](https://filamentphp.com/plugins/tharinda-rodrigo-spatie-roles-permissions#role-and-permission-policies)Role and Permission Policies

Create a RolePolicy and PermissionPolicy if you wish to control the visibility of the resources on the navigation menu. Make sure to add them to the AuthServiceProvider.

Could you explain a little bit more... I am really confused by how those policies work.

I understand we must do 

php artisan make:policy PermissionPolicy  --model=Permission
php artisan make:policy RolePolicy  --model=Role

and edit 

class AuthServiceProvider extends ServiceProvider
{
    /**
     * The model to policy mappings for the application.
     *
     * @var array<class-string, class-string>
     */
    protected $policies = [
        // 'App\Models\Model' => 'App\Policies\ModelPolicy',
       'App\Models\Role' => 'App\Policies\RolePolicy',
        'App\Models\Permission' => 'App\Policies\PermissionPolicy',

    ];

to add those policies... but... 
it does not seem to work. 
It would be great to have some clarification on how do the policies end applied.

**Comment by epertinez** [comment]
An example on how to make that only super-admin can see Role and Permision Resources (and navigation links) would be great, as I assume the same config can be extended to any other resource.

**Comment by drbyte** [comment]
Yes the same policy concepts apply to all Laravel/Filament resources:
- make the policy
- ensure it's registered to the applicable model
- write the code for the desired rules

So in the case of this package, the key is linking the policy to the correct model. If you've not extended the Spatie models into your own App namespace, then that's probably why your efforts so far aren't working.
Thus you can either link the policy to the Spatie namespaced models, or extend the models into your App. 

Here's how to do it without extending the models:

1. Create the policies:
```sh
php artisan make:policy PermissionPolicy --model=Permission
php artisan make:policy RolePolicy --model=Role
```
If you have NOT extended the Spatie Role and Permission `Models` into your own `App\Models` namespace (and you don't need to do that unless you intend to override/extend their function), then you need to edit these new Policies you just created and change `use App\Models\Role` to `use Spatie\Permission\Models\Role`. Same for Permissions.

eg:
```diff
- use App\Models\Role;
+ use Spatie\Permission\Models\Role;
```
Repeat for Permission policy.

2. Register the policies by updating the $policies array in your AuthServiceProvider:
```php
protected $policies = [
    //...
    'Spatie\Permission\Models\Role' => 'App\Policies\RolePolicy',
    'Spatie\Permission\Models\Permission' => 'App\Policies\PermissionPolicy',
];
```

3. Edit the policy logic.
The `viewAny()` method on the policy controls whether the Menu item appears in the panel. So you can add your super-user check there.
Example: 
```php
    public function viewAny(User $user): bool
    {
        if ($user->hasRole(['Super-Admin'])) {
            return true;
        }

        return false;
    }
```
Edit all the other methods of your Policies according to what you want them to allow for certain users.

**Comment by epertinez** [comment]
Thank you very much Cris. I did not have time yet to test your code but I'll do it asap.

**Comment by Cybrarist** [comment]
> Yes the same policy concepts apply to all Laravel/Filament resources:
> 
>     * make the policy
> 
>     * ensure it's registered to the applicable model
> 
>     * write the code for the desired rules
> 
> 
> So in the case of this package, the key is linking the policy to the correct model. If you've not extended the Spatie models into your own App namespace, then that's probably why your efforts so far aren't working. Thus you can either link the policy to the Spatie namespaced models, or extend the models into your App.
> 
> Here's how to do it without extending the models:
> 
>     1. Create the policies:
> 
> 
> ```shell
> php artisan make:policy PermissionPolicy --model=Permission
> php artisan make:policy RolePolicy --model=Role
> ```
> 
> If you have NOT extended the Spatie Role and Permission `Models` into your own `App\Models` namespace (and you don't need to do that unless you intend to override/extend their function), then you need to edit these new Policies you just created and change `use App\Models\Role` to `use Spatie\Permission\Models\Role`. Same for Permissions.
> 
> eg:
> 
> ```diff
> - use App\Models\Role;
> + use Spatie\Permission\Models\Role;
> ```
> 
> Repeat for Permission policy.
> 
>     2. Register the policies by updating the $policies array in your AuthServiceProvider:
> 
> 
> ```
> protected $policies = [
>     //...
>     'Spatie\Permission\Models\Role' => 'App\Policies\RolePolicy',
>     'Spatie\Permission\Models\Permission' => 'App\Policies\PermissionPolicy',
> ];
> ```
> 
>     3. Edit the policy logic.
>        The `viewAny()` method on the policy controls whether the Menu item appears in the panel. So you can add your super-user check there.
>        Example:
> 
> 
> ```
>     public function viewAny(User $user): bool
>     {
>         if ($user->hasRole(['Super-Admin'])) {
>             return true;
>         }
> 
>         return false;
>     }
> ```
> 
> Edit all the other methods of your Policies according to what you want them to allow for certain users.

please note you can use the following to block it too 
  public function before(User $user)
    {
        if ($user->hasRole(['Super-Admin'])) {
            return true;
        }

        return false;
    }

**Comment by bianchi** [comment]
In Laravel 11, because we do not have the `AuthServiceProvider`, you can insert the following line in the `boot` method of `AppServiceProvider`:

`Gate::policy(\Spatie\Permission\Models\Permission::class, YourPermissionPolicy::class);`
