### ISSUE TITLE
Are you using tenancy in Filament?

### ISSUE THREAD

**Issue by gkamaratak** [Althinect/filament-spatie-roles-permissions#121]
Are you using tenancy in Filament?

_Originally posted by @tharindarodrigo in https://github.com/Althinect/filament-spatie-roles-permissions/issues/106#issuecomment-1791105257_
            

I am using tenancy in Filament , and when I use hasRoles in User model I get the same error when i try to assign a Role to a User. Is there any trick?

**Comment by tharindarodrigo** [comment]
Please read and follow the steps in the tenancy section within the documentation.

**Comment by gkamaratak** [comment]
I have done it 4 times and on fresh installations. I cannot assign role to user as team id does not pass to the relationship. As I said you have to define the roles() relationship in User model and probably the spatie original trait does not support the team_id field.

**Comment by irvingviveros** [comment]
Hi @gkamaratak, where you able to resolve this issue? I have updated the package version on my project but still not working to attach roles to a user in the edit action, from the UserResource I’ve created, also in the User relationship from the Roles resource.

The repo maintainer says to everyone to see the documentation, but that doesn’t help, hehe.

Thank you in advanced

**Comment by gkamaratak** [comment]
Hi @irvingviveros , unfortunately I did not resolve this issue . I moved on different features i was working.
