### ISSUE TITLE
Command not found when attempting to generate policies

### ISSUE THREAD

**Issue by dannyyounes** [Althinect/filament-spatie-roles-permissions#130]
Hi, I have just installed your library, and when I attempt to run the policies command

`php artisan permissions:sync -C|--policies`

I get the following error --policies: command not found

Thanks

**Comment by tharindarodrigo** [comment]
I guess you are new to Laravel.
The '|' is just to symbolise to use either -C or --clean which does the same
`php artisan permissions:sync -C` and `php artisan permissions:sync --clean` are the same

If you want to sync permissions, generate Policies `php artisan permissions:sync -CP` or `php artisan permissions:sync --clean --policies`
