### ISSUE TITLE
Disable navigation icons

### ISSUE THREAD

**Issue by rzki** [Althinect/filament-spatie-roles-permissions#137]
Hi, is there any way to disable the navigation icons for Roles and Permissions? because i wanted to create navigation group with icon that will include Roles and Permissions inside. Since Filament doesn't support multiple icons for Navigation Groups and Items, i'm unable to do that. 

If there's any solution, it would be much appreciated. Thanks!

**Comment by tharindarodrigo** [comment]
check the config file

**Comment by rzki** [comment]
> check the config file

already checked but i think there's no options to disable there, am i wrong?

**Comment by tharindarodrigo** [comment]
I guess you are referring to Filament's latest feature. If so there is no way to do it at the moment

**Comment by rzki** [comment]
i see. well thank you for your help 👍
