### ISSUE TITLE
How to hide for other levels

### ISSUE THREAD

**Issue by pfzwaan** [Althinect/filament-spatie-roles-permissions#146]
The roles and right get assign to the menu of filament. In my system i got admins and moderators, how to i hide this extension for the moderators. I extended the spatie models and try to create the policies but i doesnot hide on the filament menu?  I dont want that moderators can assign themself permissions.

**Comment by drbyte** [comment]
> and try to create the policies but i doesnot hide on the filament menu? 

In most cases, Filament decides whether to show a resource's Nav item by checking the policy's `viewAny()` response.

**Comment by pfzwaan** [comment]
Yes that i know, for my resources this works except for this extension? Any ideas?

**Comment by pfzwaan** [comment]
PermissionPolicy and rolespolicy doesnot seem to work to hide this?

**Comment by drbyte** [comment]
When I wrote that reply in that other post, I quoted exactly the code changes I implemented, and confirmed that it worked for me with this Filament package.

Perhaps you haven't registered the policies to the correct models?

**Comment by pfzwaan** [comment]
yes was that thanks
