### ISSUE TITLE
It is not compatible with user models that do not use name attribute

### ISSUE THREAD

**Issue by lokiwich** [Althinect/filament-spatie-roles-permissions#151]
When the user model does not have a name attribute, the package returns an error on attaching users to a role or permission

![image](https://github.com/Althinect/filament-spatie-roles-permissions/assets/35873574/6ce42e69-446d-448c-954b-ad683272a058)

please add ability to customize user relation and attachment process

**Comment by drbyte** [comment]
Perhaps the `UserRelationManager` just needs to replace the static var with a helper method that loads the field name from the config:

https://github.com/Althinect/filament-spatie-roles-permissions/blob/843952afb1d46dff905571bc7af7cce4af2c96a4/src/Resources/RoleResource/RelationManager/UserRelationManager.php#L18

```diff
-    protected static ?string $recordTitleAttribute = 'name';

+    public static function getRecordTitleAttribute(): ?string
+    {
+        return config('filament-spatie-roles-permissions.user_name_column');
+    }
```

**Comment by yahya077** [comment]
Yes, I've tested it and created a PR for it, #176
