### ISSUE TITLE
sql error role_user doesn't exixt 

### ISSUE THREAD

**Issue by ivl04** [Althinect/filament-spatie-roles-permissions#152]
I got following error when I tried to edit user
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'restaurantsrewards.role_user' doesn't exist

restaurantsrewards is my database and I have added following code in authserviceprovider

```
Gate::before(function (User $user, string $ability) {
            return $user->isSuperAdmin() ? true : null;
        });
```

**Comment by tharindarodrigo** [comment]
You probably haven't migrated the tables.

**Comment by drbyte** [comment]
... or you have a conflicting `function role` relationship set up in your User model, which is overriding the spatie package
