### ISSUE TITLE
help you with customizing naming conventions

### ISSUE THREAD

**Issue by bo3bdo** [Althinect/filament-spatie-roles-permissions#161]
If i have a Post model, it will generate the following permissions

view-any Post
view Post
create Post
update Post

Can i add label for it ? Now i have model like Cat 

view-any Cat
view Cat

I want to change the name without changing the model name

![image](https://github.com/Althinect/filament-spatie-roles-permissions/assets/5271380/194c588f-7181-4e6e-89a9-d291551e7cad)

**Comment by tharindarodrigo** [comment]
Please read the configuration file. You can customize everything there
