### ISSUE TITLE
This package is not updated in Packagist

### ISSUE THREAD

**Issue by soymgomez** [Althinect/filament-spatie-roles-permissions#163]
Hi @tharindarodrigo @UdamLiyanage ,

we see that in repository version 2.2.20 has been published but in Packagist the last available version is 2.2.19.

Maybe you could activate the [auto-update feature](https://packagist.org/about#how-to-update-packages) of Packagist? So it will always be up to date.

Best regards and thank you very much!

**Comment by tharindarodrigo** [comment]
Thanks
