### ISSUE TITLE
Super Admin working, any other permission not working

### ISSUE THREAD

**Issue by goldjunge4** [Althinect/filament-spatie-roles-permissions#167]
Hello Althinect, i am having issues with getting the permissions running, but i am not sure where the issue is located.
I have installed everything according your instructions and i have added a Super Admin and everything is working fine, but when i add now a role with specific permissions (permissions generated via artisan permission:sync) and add a user to the role, the user has no access. I have also changed the view method within the policy to return true instead of the can('view_fault') and then the rights are correct. Do you have any idea what there is missing?
Thanks for your help. Armin

**Comment by paulmercs** [comment]
Up for this. Same issue as mine

**Comment by webtamizhan** [comment]
Hey @paulmercs and @goldjunge4 ,

We too have a same issue.

In our case, permission_affixes in the filament-spatie-roles-permissions.php does not match with the Policy. This is why resources are not working and don't forget to register your policies under AuthServiceProvider.php and finally don't forget to clear permissions cache.

**Comment by goldjunge4** [comment]
Hello @webtamizhan,
The issue with the different naming of permissions and in the policy was also something i found during issue checking. I have manually entered the correct name. i dont need to enter the policies under the AuthServiceProvider, this seems to be self recognized. After changing the complete policies to checkPermissionTo method and changing the name of the permissions, it is now working correctly.

**Comment by spcbfr** [comment]
@goldjunge4 the problem is happening because the super admin is assigned roles through Laravel gates directly and not manually via `assignPermissionTo` method. so `checkPermissionTo` is unable to recognize those gates and returns false for every single check, the solution is to simply use `user()->can('permission name')` instead of `checkPermissionTo`

**Comment by mahmutblt** [comment]
1- 
```
> php artisan tinker

> \Spatie\Permission\Models\Role::create(['name' => 'Super Admin']);
```

2- In the boot method of the AppServiceProvider add the following        
        
```
Gate::before(function (User $user, $ability) {
            if ($user->hasRole('Super Admin')) {
                return true;
            }
            return null;
        });
```

3- in User Model

```
    public function canAccessPanel(Panel $panel): bool
    {
        return $this->hasRole('Admin') || $this->hasRole('Super Admin');
    }
```
