### ISSUE TITLE
Does not support Permissions and Roles using a key named 'uuid'

### ISSUE THREAD

**Issue by cryptobrains** [Althinect/filament-spatie-roles-permissions#171]
I am following Spatie's process to use UUIDs instead of IDs (which replicate better) and the filament resources cannot be loaded. The change is trivial; if needed I can post a pull request.

You can get the key name with 

 `$keyName = str_replace('model_', '', config('permission.column_names.model_morph_key', 'model_id'));`
  
which needs to be changed where 'id' is used in places like PermissionResource and ListPermissions

**Comment by drbyte** [comment]
Also worth considering:
You don't "need" to use `uuid` as your column name, nor `model_uuid` as your pivot name.

You could leave the pivot name as the default of `model_id`.
And you could use `uuid('id')` instead of `uuid('uuid')` in your migration.

**Comment by cryptobrains** [comment]
True, but I would rather follow Spatie's package best practices (though optional) suggestions than carry an alternative into the future as technical debt.

**Comment by cryptobrains** [comment]
Disregard my solution above; instead I recommend that we load the id from a config key and not rely on the transformation I proposed (which is overly simplistic).
