### ISSUE TITLE
Need to help to hidden roles and permission setting in dashboard

### ISSUE THREAD

**Issue by Fakhri17** [Althinect/filament-spatie-roles-permissions#183]
When using this plugin, it will definitely create features on the dashboard like the image I attached

So I have the roles Super Admin, UMKM Owner and Customer
I want to restrict or hide roles other than Super Admin, how do I implement it?

![image](https://github.com/Althinect/filament-spatie-roles-permissions/assets/54692387/aa521721-0548-463e-927a-cd55fb2ebf49)

**Comment by abdulmannans-joistic** [comment]
@Fakhri17 how can we restrict the access?

**Comment by waelkhalifa** [comment]
@Fakhri17 Could u share with us how did u solve it?

**Comment by waelkhalifa** [comment]
@Fakhri17 Could u share with us how did u solve it?

**Comment by Fakhri17** [comment]
@abdulmannans-joistic 
> @Fakhri17 how can we restrict the access?

im just at code in AuthServiceProvider
```
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;

protected $policies = [
        // 'App\Models\Model' => 'App\Policies\ModelPolicy',
        Blog::class => BlogPolicy::class,
        BlogCategory::class => BlogCategoryPolicy::class,
        Role::class => RolePolicy::class,
        Permission::class => PermissionPolicy::class,
        ProductCategory::class => ProductCategoryPolicy::class,
        UmkmProduct::class => UmkmProductPolicy::class,
        User::class => UserPolicy::class,
    ];
    
 ```

**Comment by abdulmannans-joistic** [comment]
Thank you @Fakhri17

**Comment by fahmiegerton** [comment]
> @abdulmannans-joistic
> 
> > @Fakhri17 how can we restrict the access?
> 
> im just at code in AuthServiceProvider
> 
> ```
> use Spatie\Permission\Models\Role;
> use Spatie\Permission\Models\Permission;
> 
> protected $policies = [
>         // 'App\Models\Model' => 'App\Policies\ModelPolicy',
>         Blog::class => BlogPolicy::class,
>         BlogCategory::class => BlogCategoryPolicy::class,
>         Role::class => RolePolicy::class,
>         Permission::class => PermissionPolicy::class,
>         ProductCategory::class => ProductCategoryPolicy::class,
>         UmkmProduct::class => UmkmProductPolicy::class,
>         User::class => UserPolicy::class,
>     ];
>     
> ```

How to do it in Laravel 11 since AuthServiceProvider is not available in the project?

**Comment by pedrobruning** [comment]
Hi @fahmiegerton I got myself in the same position as you are. After following Laravel 11 [documentation ](https://laravel.com/docs/11.x/authorization#registering-policies) we can see that we should register new policies through AppServiceProvider.

AppServiceProvider.php:
```php

/**
 * Bootstrap any application services.
 */
public function boot(): void
 {
        Gate::before(function (User $user, string $ability) {
            return $user->isSuperAdmin() ? true : null;
        });

        Gate::policy(Role::class, RolePolicy::class);
        Gate::policy(Permission::class, PermissionPolicy::class);
}
```

And the Policies are the same basically, every method just checks if the user is super admin.

e.g.

```php

/**
 * Determine whether the user can view any models.
 */
public function viewAny(User $user): bool
{
        return $user->isSuperAdmin();
}
```
