### ISSUE TITLE
Why permissions:sync  command raised error ?

### ISSUE THREAD

**Issue by sergeynilov** [Althinect/filament-spatie-roles-permissions#189]
In laravel 10 / filamentphp 3 app I have installed Althinect/filament-spatie-roles-permissions package "^2.2.28"
and following instructions I got error with command :

> php artisan permissions:sync -P| --policies
> --policies: command not found
> 

I tried to edit this command in console line editing manually chars "-" and "|" with keyboard, but still
the same error. which is valid format of the command ?

Is that error critical? can I simulate it in some other way?

**Comment by tharindarodrigo** [comment]
You are running it wrong. It should be either 
`php artisan permissions:sync -P`
or
`php artisan permissions:sync --policies`
