### ISSUE TITLE
Validate route

### ISSUE THREAD

**Issue by xx1196** [Althinect/filament-spatie-roles-permissions#199]
Hi, im using filament with spatie permissions, i have this component filament

`<?php

namespace App\Filament\Resources;

use App\Filament\Resources\UserResource\Pages;
use App\Models\Dependency;
use App\Models\TypeDocument;
use App\Models\User;
use Filament\Forms;
use Filament\Forms\Form;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\SoftDeletingScope;
use Spatie\Permission\Models\Role;

class UserResource extends Resource
{
    protected static ?string $model = User::class;

    protected static ?string $navigationIcon = "heroicon-o-rectangle-stack";

    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                Forms\Components\Select::make("role")
                    ->label("Roles")
                    ->relationship("roles", "name")
                    ->options(
                        Role::all()->pluck("name", "id")
                    )
                    ->searchable()
                    ->required(),
                Forms\Components\TextInput::make("name")
                    ->label("Nombres")
                    ->required()
                    ->maxLength(200),
                Forms\Components\TextInput::make("lastname")
                    ->label("Apellidos")
                    ->required()
                    ->maxLength(200),
                Forms\Components\Select::make("type_document")
                    ->label("Tipo de identificacion")
                    ->relationship("typeDocument")
                    ->options(
                        TypeDocument::all()->pluck("name", "id")
                    )
                    ->searchable()
                    ->preload()
                    ->createOptionForm([
                        Forms\Components\TextInput::make("name")
                            ->label("Nombre del tipo de identificacion")
                            ->required()
                            ->maxLength(200)
                    ])
                    ->required(),
                Forms\Components\TextInput::make("document")
                    ->label("Numero de documento")
                    ->required()
                    ->maxLength(200),
                Forms\Components\TextInput::make("email")
                    ->label("Correo")
                    ->required()
                    ->email()
                    ->maxLength(200),
                Forms\Components\TextInput::make("position")
                    ->label("Cargo")
                    ->required()
                    ->maxLength(200),
                Forms\Components\Select::make("dependency_id")
                    ->label("Dependencia")
                    ->relationship("dependency")
                    ->options(
                        Dependency::all()->pluck("name", "id")
                    )
                    ->searchable()
                    ->preload()
                    ->required(),
                Forms\Components\TextInput::make("password")
                    ->label("Password")
                    ->required()
                    ->password()
                    ->maxLength(200),
                Forms\Components\FileUpload::make("mechanical_signature")
                    ->label("Firma mecánica")
                    ->required()
                    ->acceptedFileTypes(["image/*"])
                    ->image(),
            ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                Tables\Columns\TextColumn::make("name")
                    ->label("Nombres")
                    ->searchable(),
                Tables\Columns\TextColumn::make("lastname")
                    ->label("Apellidos")
                    ->searchable(),
                Tables\Columns\TextColumn::make("email")
                    ->label("Correo")
                    ->searchable(),
                Tables\Columns\TextColumn::make("position")
                    ->label("Cargo")
                    ->searchable(),
                /*Tables\Columns\TextColumn::make("typeDocument.name")
                    ->label("Tipo de documento"),*/
                Tables\Columns\TextColumn::make("document")
                    ->label("Documento")
                    ->searchable(),
                Tables\Columns\TextColumn::make("dependency.name")
                    ->label("Dependencia"),

            ])
            ->filters([
                Tables\Filters\SelectFilter::make("type_document_id")
                    ->options(
                        TypeDocument::all()->pluck("name", "id")
                    )
                    ->label("Tipos de documento"),
                Tables\Filters\SelectFilter::make("dependency_id")
                    ->options(
                        Dependency::all()->pluck("name", "id")
                    )
                    ->label("Dependencias"),
            ])
            ->actions([
                Tables\Actions\EditAction::make()->visible(auth()->user()->can("users.edit")),
            ])
            ->bulkActions([
                Tables\Actions\BulkActionGroup::make([
                    Tables\Actions\DeleteBulkAction::make()->visible(auth()->user()->can("users.delete")),
                ]),
            ]);
    }

    public static function getRelations(): array
    {
        return [
            //
        ];
    }

    public static function getPages(): array
    {
        return [
            "index" => Pages\ListUsers::route("/"),
            "create" => Pages\CreateUser::route("/create"),
            "edit" => Pages\EditUser::route("/{record}/edit"),
        ];
    }
}
`

how i can restric the create or edit route if i have this permission?, thanks

**Comment by drbyte** [comment]
> protected static ?string $model = User::class;

> how i can restric the create or edit route if i have this permission?

Create a Policy for the User model, restricting the create and edit methods.
https://laravel.com/docs/authorization#creating-policies

Filament uses Laravel policies to apply restrictions to Resources.
https://filamentphp.com/docs/3.x/panels/resources/creating-records#authorization
https://filamentphp.com/docs/3.x/panels/resources/editing-records#authorization
https://filamentphp.com/docs/3.x/panels/resources/deleting-records#authorization
https://filamentphp.com/docs/3.x/panels/users#authorizing-guests-in-policies
