### ISSUE TITLE
Custom Resources

### ISSUE THREAD

**Issue by hizmarck** [Althinect/filament-spatie-roles-permissions#200]
I'm wondering if in the configuration file, changing this it should change the default Resources?

`config/filament-spatie-roles-permissions.php`

```
'resources' => [
        'PermissionResource' => App\Filament\Resources\PermissionResource::class,
        'RoleResource' => App\Filament\Resources\RoleResource::class,
    ],
```

The resources there are some that I created to test, but seems to be that the plugin still continue pointing to the default ones, or am I wrong?

My configuration:

```
"php": "^8.2",
"althinect/filament-spatie-roles-permissions": "^2.2",
"filament/filament": "^3.2"
```

**Comment by tharindarodrigo** [comment]
I think you should remove the plugin from the filament panel and use your own resources. You'll still be able to generate the permissions and policies using the commands
