### ISSUE TITLE
Creating Roles in the resource

### ISSUE THREAD

**Issue by JamieCee20** [Althinect/filament-spatie-roles-permissions#210]
Unless im blind, when creating a new role in the resource, is there a way to make it automatically generate a base policy for that role? without having to run the artisan command manually

**Comment by tharindarodrigo** [comment]
No there is no way to do such thing. And I don't understand the point of generating a policy for a role. Policies are bound to models. And I don't recommend using roles directly with Policies. It is best to bind policies with permissions. 
Refer the Spatie documentation.
