### ISSUE TITLE
URGENT - EASY TO SOLVE - selecting pt_PT  TOTALLY crashes an app and the user is unable to login back

### ISSUE THREAD

**Issue by epertinez** [Althinect/filament-spatie-roles-permissions#216]
There is a problem with files in /vendor/althinect/filament-spatie-roles/resources/langs/
The file with translations to Portugal portuguese is named pt_PT, while it should be named filament-spatie.php and be inside a dir named pt_PT

That creates a big mess with error file_exists(): open_basedir restriction in effect.
File (...pt_PT/filament-spatie.php) is not within the allowed paths (...)

I assume it shows this error because it tries to jump to pt_PT directory and being a file it fails.

Solution is easy:

cd <blalbabla>/vendor/althinect/filament-spatie-roles/resources/langs/
mv pt_PT filament-spatie.php
mkdir pt_PT
mv filament-spatie.php pt_PT/

But the error can appear anytime we compose upgrade the module. So it must be solved asap (as I understand it)

**Comment by tharindarodrigo** [comment]
You can do a composer update now.

**Comment by epertinez** [comment]
Thank you very much!!!
