### ISSUE TITLE
Issue with searching users when trying to assign roles

### ISSUE THREAD

**Issue by MaartenWaegeman** [Althinect/filament-spatie-roles-permissions#221]
The fix in https://github.com/Althinect/filament-spatie-roles-permissions/pull/215 didn't end up solving the problem of having default search colum values.

![image](https://github.com/user-attachments/assets/91fcca68-129d-46b0-a95b-471681fc4004)

I don't have my config file published, so I'm using all the default values. In src/Resources/RoleResource/RelationManager/UserRelationManager.php this code snippet always returns null.
`config('filament-spatie-roles-permissions.user_name_searchable_columns', 'name')`

The solution to fix it, is to comment out L107 in the configuration file.
https://github.com/Althinect/filament-spatie-roles-permissions/blob/e5ccc0e2e8b324cbe591005dffc04b1269688b7d/config/filament-spatie-roles-permissions.php#L107

Then the config function should return the correct "name" default value.

**Comment by tharindarodrigo** [comment]
Added a fix
