### ISSUE TITLE
Column::searchable(): Argument #1 ($condition) must be of type array|string|bool

### ISSUE THREAD

**Issue by mrvnklm** [Althinect/filament-spatie-roles-permissions#223]
I get the following error on users relationmanager for roles:
`
Filament\Tables\Columns\Column::searchable(): Argument #1 ($condition) must be of type array|string|bool, null given, called in /Users/mrvn/main/vendor/althinect/filament-spatie-roles-permissions/src/Resources/RoleResource/RelationManager/UserRelationManager.php on line 61
`

**Comment by JamieCee20** [comment]
I've also just noticed this error, and im unable to find out whats causing it.

**Comment by tharindarodrigo** [comment]
This was fixed in the last update. Make sure to do a `composer update`. if you have published your config file, make sure it has the following.
`'user_name_searchable_columns' => 'name',`
