### ISSUE TITLE
Restricting access

### ISSUE THREAD

**Issue by albertobenavides** [Althinect/filament-spatie-roles-permissions#41]
Hello, is there a way to restrict access to roles and permissions tables and views based on policies or middleware? 

Thank you in advance.

**Comment by albertobenavides** [comment]
Ok, I found how to do it:

1. Create a Policy for Roles with `php artisan make:policy RolePolicy --model=Spatie\Permission\Models\Role`
2. Change line 5 to `use Spatie\Permission\Models\Role;`
3. In AuthServiceProvider.php add this policy: 
```php
use App\Policies\RolePolicy;
use Spatie\Permission\Models\Role;
// ...
protected $policies = [
    // ...
    Role::class => RolePolicy::class
];

The same applies to permissions.
```

**Comment by pnm1231** [comment]
You could also add Spatie models to the `config/filament-spatie-roles-permissions.php` file and let the permission and role sync commands do the needful.

```php
'custom_models' => [
    \Spatie\Permission\Models\Role::class,
    \Spatie\Permission\Models\Permission::class,
 ],
```

**Comment by DanielVera987** [comment]
Hi, I am try implement @pnm1231 your solution, for not working

**Comment by monteduro** [comment]
> You could also add Spatie models to the `config/filament-spatie-roles-permissions.php` file and let the permission and role sync commands do the needful.
> 
> ```
> 'custom_models' => [
>     \Spatie\Permission\Models\Role::class,
>     \Spatie\Permission\Models\Permission::class,
>  ],
> ```

But still need to add the policies to AuthServiceProvider.php, right?
