### ISSUE TITLE
option to hide guard in forms

### ISSUE THREAD

**Issue by ankorinek** [Althinect/filament-spatie-roles-permissions#45]
Is there a config option to hide the guard input in the forms when there is only the default web guard installed?

**Comment by tharindarodrigo** [comment]
Added the option select guard_name
you can set the default guard_name in the config file(Make sure to force publish with caution)

**Comment by aurawindsurfing** [comment]
Hi I believe @ankorinek did not want his users to see it at all in the form. Is there option to make it hidden?

**Comment by aurawindsurfing** [comment]
I can make a pull request if you will accept it, other then that we need to extent your clas and overwrite the form method to hide this field.

**Comment by tharindarodrigo** [comment]
Please do send a PR
