### ISSUE TITLE
Need little help

### ISSUE THREAD

**Issue by PKDmeDEV** [Althinect/filament-spatie-roles-permissions#52]
Hi,
I have just tried the package. All the earlier listed resources in the panel are not visible any more to me. 
Only Roles and Permissions are listed.
I have not created SuperAdmin role yet and assigned to user. Is it mandatory ?
I was using a `admin` role and was validating to access filament admin panel from User model, with `canAccessFilament` method.

Can you provide some more details, what I need to do to bring it back.

Thanks

**Comment by PKDmeDEV** [comment]
So after adding `Super Admin` role and assign it to user, it works.

**Comment by tharindarodrigo** [comment]
If you create have generated policies, filament will automatically apply them to the resources. The Super admin role  overrides all policies from a Gate. Therefore the super admin has unrestricted access to all resources. Probably this is what happened in your case.
So you'll have to assign the permissions to a role and assign the role to a user.

**Comment by PKDmeDEV** [comment]
Thanks for the reply,

But, I noticed when I run migrate:refresh, all permission (except seeded
ones) are gone. In that case, what permissions remain ? that may require to
be add to any role for it to see all resources.

**Comment by tharindarodrigo** [comment]
You'll have to run `php artisan permissions:sync`. 
Please refer the documentation.
https://github.com/Althinect/filament-spatie-roles-permissions#generate-permissions

If you want custom permissions you can add them in the config file.
As long as you run the above command after you run migrate:fresh (my recommendation over the refresh command)
All the configured permissions will be seeded. You don't need to add separate permission seeders.

**Comment by PKDmeDEV** [comment]
Got it. Will play with it more to understand better.

Thanks
