### ISSUE TITLE
Attempts to instantiate abstract classes

### ISSUE THREAD

**Issue by SychO9** [Althinect/filament-spatie-roles-permissions#53]
Hello 👋🏼,

Nice package! 

I am not entirely sure why this is happening *now* specifically as I've had the abstract class for a little while. But the package seems to attempt to instantiate non-concrete classes.

https://github.com/Althinect/filament-spatie-roles-permissions/blame/4734c9a1cd93c31ed1fa75499880e8f21b708465/src/Commands/Permission.php#L176

![image](https://github.com/Althinect/filament-spatie-roles-permissions/assets/20267363/a3b7dabf-952c-4c85-a6b7-62fa7b28393a)

**Comment by tharindarodrigo** [comment]
Will be looking into this

**Comment by tharindarodrigo** [comment]
@SychO9 
When does this happen? 
Do you have a manual trigger (an Action maybe) on the UI to run the command?

**Comment by SychO9** [comment]
@tharindarodrigo When accessing the permissions filament, there's no custom changes/behavior related to the package, all default.

**Comment by tharindarodrigo** [comment]
Do you mean when you access the 
http://url.test/admin/permissions page?

**Comment by tharindarodrigo** [comment]
@SychO9 I found the issue. The last update to filter permissions by model names has caused this issue.
Sorry about the delay. I have added a fix for this
