### ISSUE TITLE
The cache is not cleared when permissions are added to or removed from roles

### ISSUE THREAD

**Issue by mkeremcansev** [Althinect/filament-spatie-roles-permissions#62]
When creating a new role, it clears the cache; after deleting a role, it clears the cache as well. However, it does not clear the cache when making permission updates within a role.

```
->actions([
    Tables\Actions\DeleteAction::make(),
    Tables\Actions\EditAction::make(),
    Tables\Actions\DetachAction::make()->after(function (){
        app(PermissionRegistrar::class)->forgetCachedPermissions();
    })
])
```
Adding such a table action within the PermissionRelationManager class resolves the issue, but there needs to be an update on the package side.

**Comment by tharindarodrigo** [comment]
I'd be glad to accept a PR
