### ISSUE TITLE
FR translation

### ISSUE THREAD

**Issue by sheepbild** [Althinect/filament-spatie-roles-permissions#79]
Hello,
Here is the FR translation :)
Thank you !

`<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Fields
    |--------------------------------------------------------------------------
    */

    'field.guard_name' => 'Intitulé du Garde',
    'field.permissions_count' => 'Permissions',
    'field.name' => 'Intitulé',
    'field.permissions' => 'Permissions',
    'field.roles' => 'Rôles',
    'field.role' => 'Rôle',
    'field.team' => 'Équipe',

    /*
    |--------------------------------------------------------------------------
    | Labels
    |--------------------------------------------------------------------------
    */

    'section.permission' => 'Permission',
    'section.permissions' => 'Permissions',
    'section.role' => 'Rôle',
    'section.roles' => 'Rôles',
    'section.roles_and_permissions' => 'Rôles et Permissions',
    'select-team' => 'Sélectionnez une Équipe',
    'select-team-hint' => 'Laissez vide pour un rôle global',
    'section.users' => 'Utilisateurs',
];
`

**Comment by tharindarodrigo** [comment]
Hi can you please send a PR?
