### ISSUE TITLE
Need to update forms  'Filament\Forms\Components\Card' 

### ISSUE THREAD

**Issue by gyaanesh** [Althinect/filament-spatie-roles-permissions#84]
the current version has `  Card::make()` in form methods which is now deprecated please replace it with `Section::make()`
![image](https://github.com/Althinect/filament-spatie-roles-permissions/assets/43063785/7b0b02a1-6fc9-4c67-b6eb-90268f57dcde)
to 
![image](https://github.com/Althinect/filament-spatie-roles-permissions/assets/43063785/b9a35668-042d-41b6-8700-7756aef23d90)

**Comment by tharindarodrigo** [comment]
You should look in to Spatie's documentation on that.
What I encourage you is to create a Role, assign the permissions to the Role and then assign the Role to the user.
