### ISSUE TITLE
User name column config parameter is not correct.

### ISSUE THREAD

**Issue by NaungYeHtet** [Althinect/filament-spatie-roles-permissions#87]
Althinect\FilamentSpatieRolesPermissions\Resources\RoleResource\RelationManager\UserRelationManager;

TextInput::make(config('filament-spatie-roles-permissions.user_name_column'))

Should Be 

TextInput::make(config('filament-spatie-roles-permissions.generator.user_name_column'))

**Comment by pnm1231** [comment]
This is fixed in https://github.com/Althinect/filament-spatie-roles-permissions/pull/90
