### ISSUE TITLE
Problem with Tenant/teams

### ISSUE THREAD

**Issue by fmargerit** [Althinect/filament-spatie-roles-permissions#91]
Hi,
i have a problem with tenants.

**The model [Spatie\Permission\Models\Role] does not have a relationship named [team]. You can change the relationship being used by passing it to the [ownershipRelationship] argument of the [tenant()] method in configuration. You can change the relationship being used per-resource by setting it as the [$tenantOwnershipRelationshipName] static property on the [Althinect\FilamentSpatieRolesPermissions\Resources\RoleResource] resource class.**

Can you give me an solution for this problem ?

Thank's !

**Comment by hwtdnet** [comment]
I also encountered this problem

**Comment by fmargerit** [comment]
> I also encountered this problem

Did you find any solution ?

**Comment by hwtdnet** [comment]
@fmargerit No, Wait this Developer.

**Comment by juliangums** [comment]
The link doesn't work for me.

You could set $tenantOwnershipRelationshipName in the resource files but it doesn't look like the Spatie Permission or Role Models have any relationship. So you'd probably have to extend them adding a team() relationship and then specifying 'team' as $tenantOwnershipRelationshipName

Doesn't feel like the most elegant solution but can't think of a better one right now.

**Comment by juliangums** [comment]
btw I also had an issue keeping Spatie Permission tenants and Filament tenant in sync and I had to write this middleware for it:
```
<?php

namespace App\Http\Middleware;

use Closure;
use Filament\Facades\Filament;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;

class SyncSpatiePermissionsWithFilament
{
    /**
     * Handle an incoming request.
     *
     * @param Closure(Request): (Response) $next
     */
    public function handle(Request $request, Closure $next): Response
    {
        $filament = Filament::getTenant()->id;
        $spatie = getPermissionsTeamId();
        if ($filament !== $spatie) {
            setPermissionsTeamId($filament);
        }

        return $next($request);
    }
}

```
and add it to the panel
```
            ->tenantMiddleware([
                SyncSpatiePermissionsWithFilament::class,
            ], isPersistent: true)
```

**Comment by edward-pham** [comment]
I extend Spatie\Permission\Models\Role model and add team() relationship, this issue has gone.

**Comment by juliangums** [comment]
Yeah that's what I am doing for now too but not really an ideal solution. I also opened a discussion on Spatie Permission to just add the relationship there as that way there's no need to extend the model here and it would be useful for other use-cases too. You can join the discussion https://github.com/spatie/laravel-permission/discussions/2518

**Comment by juliangums** [comment]
> btw I also had an issue keeping Spatie Permission tenants and Filament tenant in sync and I had to write this middleware for it:
> 
> ```
> <?php
> 
> namespace App\Http\Middleware;
> 
> use Closure;
> use Filament\Facades\Filament;
> use Illuminate\Http\Request;
> use Symfony\Component\HttpFoundation\Response;
> 
> class SyncSpatiePermissionsWithFilament
> {
>     /**
>      * Handle an incoming request.
>      *
>      * @param Closure(Request): (Response) $next
>      */
>     public function handle(Request $request, Closure $next): Response
>     {
>         $filament = Filament::getTenant()->id;
>         $spatie = getPermissionsTeamId();
>         if ($filament !== $spatie) {
>             setPermissionsTeamId($filament);
>         }
> 
>         return $next($request);
>     }
> }
> ```
> 
> and add it to the panel
> 
> ```
>             ->tenantMiddleware([
>                 SyncSpatiePermissionsWithFilament::class,
>             ], isPersistent: true)
> ```

@tharindarodrigo this might be something that should be added to this package though. Thoughts?

**Comment by tharindarodrigo** [comment]
@juliangums Would you mind sending a PR?

**Comment by juliangums** [comment]
@tharindarodrigo done https://github.com/Althinect/filament-spatie-roles-permissions/pull/94

**Comment by fmargerit** [comment]
Okay, good job !
