### ISSUE TITLE
Multi-tenancy: Problem when attach global role to user

### ISSUE THREAD

**Issue by edward-pham** [Althinect/filament-spatie-roles-permissions#92]
In Multi-tenancy mode, when i try to attach a global role to user, i got this error message:

SQLSTATE[HY000]: General error: 1364 Field 'team_id' doesn't have a default value
INSERT INTO `model_has_roles` (`model_id`, `model_type`, `role_id`) VALUES (1, App\Models\USER, 5)

**Comment by tharindarodrigo** [comment]
I don't think the concept of a global role is possible here. You will need select the tenant manually for now. I guess this is the best solution right now.
https://github.com/Althinect/filament-spatie-roles-permissions/issues/91#issuecomment-1763525669.

I'll try to add a solution soon.

**Comment by erenergul** [comment]
> I don't think the concept of a global role is possible here. You will need select the tenant manually for now. I guess this is the best solution right now. [#91 (comment)](https://github.com/Althinect/filament-spatie-roles-permissions/issues/91#issuecomment-1763525669).
> 
> I'll try to add a solution soon.

I tried to add solution and use middleware but Im not sure why i get this error.

Call to a member function id() on null

I can't get tenant id ->         $filament = Filament::getTenant()->id;

Couldnt figure it out. Please let me know. If you have any idea.

**Comment by pthhung1997** [comment]
> > I don't think the concept of a global role is possible here. You will need select the tenant manually for now. I guess this is the best solution right now. [#91 (comment)](https://github.com/Althinect/filament-spatie-roles-permissions/issues/91#issuecomment-1763525669).
> > I'll try to add a solution soon.
> 
> I tried to add solution and use middleware but Im not sure why i get this error.
> 
> Call to a member function id() on null
> 
> I can't get tenant id -> $filament = Filament::getTenant()->id;
> 
> Couldnt figure it out. Please let me know. If you have any idea.

I think the reason is you are in admin panel and no tenant was selected.

**Comment by pthhung1997** [comment]
> I don't think the concept of a global role is possible here. You will need select the tenant manually for now. I guess this is the best solution right now. [#91 (comment)](https://github.com/Althinect/filament-spatie-roles-permissions/issues/91#issuecomment-1763525669).
> 
> I'll try to add a solution soon.

![image](https://github.com/Althinect/filament-spatie-roles-permissions/assets/26035552/0c9fa6d7-150f-4563-9684-394f638b4730)
This form make me confuse in this case. And when i select team in this form, the team_id cannot saved with role, null value will be set for team_id. Please check it out.

One more think, i check document in spatie [teams permissions](https://spatie.be/docs/laravel-permission/v5/basic-usage/teams-permissions#content-roles-creating) too, they said when team_id is null, global role will be created and any tenant can use this role.

**Comment by tharindarodrigo** [comment]
This was implemented before tenancy was introduced in Filament 2. 
It augmented the team feature given in Spatie's package. Therefore you cannot use it while using tenancy. I'll add a PR to mitigate future confusions.
