### ISSUE TITLE
After upgrading from filament 2 to filament 3 Roles and Permissions resources do not show anymore in the Panel. Any help?

### ISSUE THREAD

**Issue by epertinez** [Althinect/filament-spatie-roles-permissions#96]
After upgrading from filament 2 to filament 3 Roles and Permissions resources do not show anymore in the Panel. 
Is there anything I have to check? Any new way those resources are hooked to User? Never  knew how those resources appeared automagically in the navigation menu, anyway...

**Comment by tharindarodrigo** [comment]
There is no new way. But certainly there are some additions on 2.x branch
Please read the documentation and follow accordingly. 
There is no such issue as of now.

**Comment by epertinez** [comment]
Thanks
I had to add the plugin to the admin panel. In my case the AppPanelProvider.

->plugin(FilamentSpatieRolesPermissionsPlugin::make())
