### ISSUE TITLE
Adding a 	Guard Name filter

### ISSUE THREAD

**Issue by manojhl** [Althinect/filament-spatie-roles-permissions#97]
I think adding a filter for guard name makes it easier to filter the permissions available

**Comment by tharindarodrigo** [comment]
You can configure guard name in the config file. However there is no Filter on the tables as of now. Feel free to send in a PR

**Comment by badcom** [comment]
@tharindarodrigo is it possible to set a defaultSort() to a specific column for both Roles and Permissions?

**Comment by tharindarodrigo** [comment]
At the moment No. You'll have to extend the resource and override the table method.
