### ISSUE TITLE
Policy for Roles

### ISSUE THREAD

**Issue by rajubeparybd** [Althinect/filament-spatie-roles-permissions#98]
A `Policy`, in my opinion, is essential for a `Role` model. After entering the admin panel, the user may now create a role. Assume that a user's only rights are to create and edit users. However, he can create a new role with all permissions by accessing the role through the URL and getting access to the full application.

**Comment by tharindarodrigo** [comment]
Yes you can create a policy for the Role and add it in the Auth Service Provider mapped with the Spatie's models
